# Generated by Django 5.0.4 on 2024-04-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('publication', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ('name', models.CharField(max_length=50)),
                ('bread', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to="users/%d/%m/%Y", verbose_name="Фотография")),
                ('happy_birth', models.DateTimeField(blank=True, null=True, verbose_name="Дата рождения")),
                ('character', models.CharField(max_length=500)),
                ('can', models.CharField(max_length=500)),
                ('delicacy', models.CharField(max_length=500)),
                ('byaka', models.CharField(blank=True, max_length=500)),
                ('favorite', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
