# Generated by Django 5.0.4 on 2024-04-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-time_create']},
        ),
        migrations.AlterField(
            model_name='material',
            name='publication',
            field=models.BooleanField(choices=[(0, 'Приватно'), (1, 'Опубликовано')], default=0),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['-time_create'], name='pet_materia_time_cr_747528_idx'),
        ),
    ]
