# Generated by Django 5.0.4 on 2024-04-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet',
            new_name='MyPet',
        ),
    ]
