# Generated by Django 5.0.4 on 2024-04-23 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_material_options_alter_material_publication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='elem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pet.element'),
            preserve_default=False,
        ),
    ]
