# Generated by Django 5.0.4 on 2024-04-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_rename_pet_mypet'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='slug',
            field=models.SlugField(default=1, max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
