# Generated by Django 5.0.4 on 2024-04-23 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_element_material_elem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=30)),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='elem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='pet.element'),
        ),
        migrations.AddField(
            model_name='material',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='pet.tagpost'),
        ),
    ]
