# Generated by Django 5.0.4 on 2024-04-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_material_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='publication',
            field=models.BooleanField(choices=[(0, 'Приватно'), (1, 'Опубликовано')], default=1),
        ),
    ]
