# Generated by Django 5.0.4 on 2024-04-23 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_tagpost_alter_material_elem_material_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-time_create'], 'verbose_name': 'Мир животных', 'verbose_name_plural': 'Мир животных'},
        ),
        migrations.AddField(
            model_name='material',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%d/%m/%Y', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Элемент'),
        ),
        migrations.AlterField(
            model_name='material',
            name='elem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='pet.element', verbose_name='Элемент'),
        ),
        migrations.AlterField(
            model_name='material',
            name='publication',
            field=models.BooleanField(choices=[(False, 'Приватно'), (True, 'Опубликовано')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='pet.tagpost', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='material',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='material',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего редактирования'),
        ),
    ]
