# Generated by Django 5.0.4 on 2024-04-19 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_material_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=70)),
                ('slug', models.SlugField(max_length=70, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='typepost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pet.typepost'),
            preserve_default=False,
        ),
    ]
