# Generated by Django 5.0.4 on 2024-04-19 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_typepost_material_typepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=30)),
                ('slug', models.SlugField(max_length=70, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='typepost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='pet.typepost'),
        ),
        migrations.AddField(
            model_name='material',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='pet.tagposts'),
        ),
    ]
