# Generated by Django 5.0.4 on 2024-04-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_uploadfields_alter_element_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Файл'),
        ),
    ]
