# Generated by Django 5.0.4 on 2024-04-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_tagposts_alter_material_typepost_material_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-time_create'], 'verbose_name': 'Мир животных', 'verbose_name_plural': 'Мир животных'},
        ),
        migrations.AlterModelOptions(
            name='mypet',
            options={'verbose_name': 'Мой питомец', 'verbose_name_plural': 'Мои питомцы'},
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['-time_create'], name='pet_materia_time_cr_747528_idx'),
        ),
        migrations.AddField(
            model_name='mypet',
            name='animal',
            field=models.OneToOneField(default=1, max_length=50, on_delete=django.db.models.deletion.PROTECT, related_name='animal', to='pet.animal'),
            preserve_default=False,
        ),
    ]
