# Generated by Django 5.0.4 on 2024-04-19 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_animal_alter_material_options_alter_mypet_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload_fiel')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tagposts',
            options={'verbose_name': 'Тип поста', 'verbose_name_plural': 'Тип поста'},
        ),
        migrations.AlterModelOptions(
            name='typepost',
            options={'verbose_name': 'Тип поста', 'verbose_name_plural': 'Тип поста'},
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='material',
            name='publication',
            field=models.BooleanField(choices=[(False, 'Приватно'), (True, 'Опубликовано')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(max_length=70, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='pet.tagposts', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='material',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='material',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего редактирования'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='material',
            name='typepost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='pet.typepost', verbose_name='Тип поста'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='animal',
            field=models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.PROTECT, related_name='animal', to='pet.animal', verbose_name='Вид питомца'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='bread',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='byaka',
            field=models.CharField(blank=True, max_length=500, verbose_name='Что не любит?'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='can',
            field=models.CharField(max_length=500, verbose_name='Что умеет?'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='character',
            field=models.CharField(max_length=500, verbose_name='Характер'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='delicacy',
            field=models.CharField(max_length=500, verbose_name='Любимая еда'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='favorite',
            field=models.CharField(blank=True, max_length=500, verbose_name='Что любит?'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tagposts',
            name='tag',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='typepost',
            name='name',
            field=models.CharField(db_index=True, max_length=70, verbose_name='Тип поста'),
        ),
    ]
