# Generated by Django 5.0.4 on 2024-04-23 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_material_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Категирия', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='material',
            name='elem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='pet.element', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tagpost',
            name='tag',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Тег'),
        ),
    ]
