# Generated by Django 5.0.4 on 2024-04-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_alter_element_options_alter_element_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFields',
            new_name='UploadFieles',
        ),
    ]
