# Generated by Django 5.0.4 on 2024-04-23 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_rename_uploadfields_uploadfieles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('bread', models.CharField(blank=True, max_length=50, null=True, verbose_name='Порода')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/', verbose_name='Фотография')),
                ('happy_birth', models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')),
                ('character', models.CharField(max_length=600, verbose_name='Характер')),
                ('can', models.CharField(max_length=600, verbose_name='Что умеет?')),
                ('delicacy', models.CharField(max_length=600, verbose_name='Любимая еда')),
                ('foo', models.CharField(blank=True, max_length=600, verbose_name='Что не любит?')),
                ('favorite', models.CharField(blank=True, max_length=600, verbose_name='Что любит?')),
                ('animal', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.PROTECT, related_name='animal', to='pet.animal', verbose_name='Вид питомца')),
            ],
            options={
                'verbose_name': 'Мой питомец',
                'verbose_name_plural': 'Мои питомцы',
            },
        ),
    ]
