# Generated by Django 5.0.4 on 2024-04-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_animal_mypet'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='slug',
            field=models.SlugField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Животное'),
        ),
    ]
