# Generated by Django 5.0.4 on 2024-04-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_animal_mypet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypet',
            name='slug',
        ),
    ]
