# Generated by Django 5.0.4 on 2024-04-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_alter_mypet_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='slug',
            field=models.SlugField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypet',
            name='slug',
            field=models.SlugField(default=1, max_length=70, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
