# Generated by Django 5.0.4 on 2024-05-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0015_material_author_alter_mypet_animal_alter_mypet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypet',
            name='animal',
            field=models.CharField(max_length=50, verbose_name='Вид животного'),
        ),
        migrations.RemoveField(
            model_name='material',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='TagPost',
        ),
    ]
